# Force Yamaha Steinberg IXO12 and Logitech Yeti to only allow 48kHz
# Prevents games from requesting 44.1kHz and causing resampling conflicts
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.usb-Yamaha*" }
      { node.name = "~alsa_input.usb-Yamaha*" }
      { node.name = "~alsa_input.usb-Logitech*" }
    ]
    actions = {
      update-props = {
        audio.rate = 48000
        audio.allowed-rates = [ 48000 ]
        api.alsa.period-size = 512
        api.alsa.headroom = 256
      }
    }
  }
]
