# -*- conf -*-
# Foot terminal config — no-clown-fiesta theme

[main]
font=CommitMonoNerdFontMono-Regular.otf:size=11
dpi-aware=yes

[colors-dark]
alpha=1.0
background=151515
foreground=E1E1E1

## Normal colors
regular0=151515   # black
regular1=b46958   # red
regular2=90A959   # green
regular3=F4BF75   # yellow
regular4=BAD7FF   # blue
regular5=AA759F   # magenta
regular6=88afa2   # cyan
regular7=E1E1E1   # white

## Bright colors
bright0=373737    # bright black (gray)
bright1=FFA557    # bright red (orange)
bright2=90A959    # bright green
bright3=F4BF75    # bright yellow
bright4=BAD7FF    # bright blue
bright5=AA749F    # bright magenta (purple)
bright6=A2B5C1    # bright cyan (medium gray-blue)
bright7=E1E1E1    # bright white

## Selection
selection-foreground=151515
selection-background=D0D0D0

## Misc
jump-labels=000000 90A959
urls=7E97AB
