# Force PulseAudio compatibility layer to use consistent settings
pulse.properties = {
    pulse.default.req      = 1024/48000    # ~21ms
    pulse.min.req          = 512/48000     # ~10.6ms
    pulse.default.format   = S16
    pulse.default.position = [ FL FR ]
}

stream.properties = {
    resample.quality = 4
}
