# window theme
include luna.config
gaps inner 6px
default_border pixel 2px
smart_borders off
# luna colors
# Property Name         Border  BG      Text    Indicator Child Border
# Property Name         Border  BG      Text    Indicator Child Border
client.focused          $silver $bg     $fg     $silver $silver
client.focused_inactive $bg_alt $bg_alt $grey   $border $bg_alt
client.unfocused        $bg     $bg     $comment $border $bg
client.urgent           $error  $error  $bg     $error  $error
client.placeholder      $bg     $bg     $comment $bg     $bg
client.background       $white

# Monitor configuration
#DP-3 MSI MAG 274QPF X30MV - Primary monitor (left)
output DP-3 mode 2560x1440@300Hz pos 0 0 scale 1 adaptive_sync on
#HDMI-1-A MSI MAG 274QPF X30MV - Primary monitor (left)
#output HDMI-A-1 mode 2560x1440@300Hz pos 0 0 scale 1 adaptive_sync off
# DP-1: Vertical monitor (right of DP-3)
output DP-1 mode 2560x1440@165Hz pos 2560 0 transform 90 scale 1 adaptive_sync on 

# Assign workspaces to outputs
workspace 1 output DP-3
workspace 2 output DP-3
workspace 3 output DP-3
workspace 4 output DP-3
workspace 5 output DP-3
workspace 6 output DP-1
workspace 7 output DP-1
workspace 8 output DP-1
workspace 9 output DP-1
workspace 10 output DP-1

# Wallpaper
output "DP-3" bg #060606 solid_color
output "DP-1" bg #060606 solid_color

# Stop screen lock if an app is fullscreen
for_window [class=".*"] inhibit_idle fullscreen
for_window [app_id=".*"] inhibit_idle fullscreen
# Screenshots:
# Super+P: Current window
# Super+Shift+p: Select area
# Super+Alt+p Current output
# Super+Ctrl+p Select a window
bindsym Mod4+p       exec grimshot save area
bindsym Mod4+Shift+p exec grimshot save window
